# GingerOS Configuration File
# ---------------------------

# LFS Settings
LFS_VERSION=12.4
LFS_MOUNT=/mnt/lfs
BUILD_TYPE=image

# Image Settings
IMAGE_NAME=ginger_os.img
IMAGE_SIZE=20G

# Architecture
LFS_TGT=x86_64-lfs-linux-gnu

# Core Toolchain Versions
BINUTILS_VERSION=2.45
GCC_VERSION=15.2.0
GLIBC_VERSION=2.42
LINUX_VERSION=6.16.1
MPFR_VERSION=4.2.2
GMP_VERSION=6.3.0
MPC_VERSION=1.3.1
