[project]
name = "ginger-os"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.136.1",
    "uvicorn>=0.46.0",
    "rich>=13.0.0",
    "ruff>=0.15.12",
    "beautifulsoup4>=4.14.3",
    "langchain>=1.2.17",
    "openai>=2.34.0",
    "faiss-cpu>=1.13.2",
    "langchain-text-splitters>=1.1.2",
    "langchain-openai>=1.2.1",
    "langchain-community>=0.4.1",
    "langchain-ollama>=1.1.0",
    "chardet>=7.4.3",
    "langchain-classic>=1.0.6",
    "chromadb>=0.8.1",
    "langchain-chroma>=1.1.0",
    "textual>=8.2.5",
    "psutil>=7.2.2",
]
