#!/usr/bin/env bash
# GingerOS – LFS 13.0 Central Version Constants
# --------------------------------------------------------------
# This file is sourced by config/env.sh and provides a single source
# of truth for all package version numbers used throughout the build.
# --------------------------------------------------------------

# LFS release
export LFS_VERSION="13.0"
export LFS_MOUNT="/mnt/ginger_lfs"

# Core toolchain
export BINUTILS_VERSION="2.46.0"
export GCC_VERSION="15.2.0"
export GLIBC_VERSION="2.43"
export LINUX_VERSION="6.18.10"
export MPFR_VERSION="4.2.2"
export GMP_VERSION="6.3.0"
export MPC_VERSION="1.3.1"

# Basic system software (alphabetical)
export M4_VERSION="1.4.21"
export NCURSES_VERSION="6.6"
export BASH_VERSION="5.3"
export COREUTILS_VERSION="9.10"
export DIFFUTILS_VERSION="3.12"
export FILE_VERSION="5.46"
export FINDUTILS_VERSION="4.10.0"
export GAWK_VERSION="5.3.2"
export GREP_VERSION="3.12"
export GZIP_VERSION="1.14"
export MAKE_VERSION="4.4.1"
export PATCH_VERSION="2.8"
export SED_VERSION="4.9"
export TAR_VERSION="1.35"
export XZ_VERSION="5.8.2"
export BZIP2_VERSION="1.0.8"
export ZLIB_VERSION="1.3.2"
export LZ4_VERSION="1.10.0"
export ZSTD_VERSION="1.5.7"
export READLINE_VERSION="8.3"
export BC_VERSION="7.0.3"
export FLEX_VERSION="2.6.4"
export TCL_VERSION="8.6.17"
export EXPECT_VERSION="5.45.4"
export DEJAGNU_VERSION="1.6.3"
export PKGCONF_VERSION="2.5.1"
export MAN_DB_VERSION="2.13.1"
export MAN_PAGES_VERSION="6.17"
export ATTR_VERSION="2.5.2"
export ACL_VERSION="2.3.2"
export LIBCAP_VERSION="2.77"
export LIBXCRYPT_VERSION="4.5.2"
export SHADOW_VERSION="4.19.3"
export PSMISC_VERSION="23.8"
export GETTEXT_VERSION="1.0"
export BISON_VERSION="3.8.2"
export LIBTOOL_VERSION="2.5.4"
export GDBM_VERSION="1.26"
export GPERF_VERSION="3.3"
export EXPAT_VERSION="2.7.4"
export INETUTILS_VERSION="2.7"
export LESS_VERSION="692"
export PERL_VERSION="5.41.3"
export XML_PARSER_VERSION="2.47"
export INTLTOOL_VERSION="0.51.0"
export AUTOCONF_VERSION="2.72"
export AUTOMAKE_VERSION="1.18.1"
export OPENSSL_VERSION="3.6.1"
export KMOD_VERSION="34.2"
export ELFUTILS_VERSION="0.194"
export LIBFFI_VERSION="3.5.2"
export PYTHON_VERSION="3.14.3"
export WHEEL_VERSION="0.46.3"
export SETUPTOOLS_VERSION="82.0.0"
export PACKAGING_VERSION="26.0"
export FLIT_CORE_VERSION="3.12.0"
export NINJA_VERSION="1.13.2"
export MESON_VERSION="1.10.1"
export CHECK_VERSION="0.15.2"
export GROFF_VERSION="1.23.0"
export GRUB_VERSION="2.14"
export IPROUTE2_VERSION="6.18.0"
export KBD_VERSION="2.9.0"
export LIBPIPELINE_VERSION="1.5.8"
export TEXINFO_VERSION="7.2"
export VIM_VERSION="9.2.0078"
export MARKUPSAFE_VERSION="3.0.3"
export JINJA2_VERSION="3.1.6"
export UDEV_VERSION="259.1"
export SYSTEMD_VERSION="259.1"
export PCRE2_VERSION="10.47"
export SQLITE_VERSION="3.51.200"
export TZDATA_VERSION="2025c"
export PROCPS_NG_VERSION="4.0.6"
export UTIL_LINUX_VERSION="2.41.3"
export E2FSPROGS_VERSION="1.47.3"
export SYSLOGD_VERSION="2.7.2"
export SYSVINIT_VERSION="3.14"
export BOOTSCRIPTS_VERSION="20250827"
export IANA_ETC_VERSION="20260202"
export LIBBURN_VERSION="1.5.6"
export LIBISOFS_VERSION="1.5.6"
export LIBISOBURN_VERSION="1.5.6"

# Export the LFS variable (may be overridden later if inside chroot)
export LFS="$LFS_MOUNT"
